### ISSUE TITLE
Custom Launcher Errors in CI Mode

### ISSUE THREAD

**Issue by semperos** [testem/testem#131]
I've configured a custom launcher as follows:

```yaml
launchers:
  Node:
    command: "mocha -R tap test/*_test.js"
    protocol: "tap"
launch_in_dev:
  - Node
  - Chrome
launch_in_ci:
  - Node
  - Chrome
```

I've introduced code in my tests that causes a JavaScript ReferenceError. You can replicate the same with something as simple as `f = new Foo()` without defining `Foo`. When I run this with Mocha by itself, I see the stacktrace and Mocha exits with an exit code of `1`, as expected. When I run the same Mocha command as a custom launcher via Testem, the stacktrace is not shown and Testem exits with an exit code of `0`.

[ADDITION]
I forgot to add that this is happening in **CI mode,** not in dev mode.
[/ADDITION]

Can anyone shed light on why this is the case? This ends up silently swallowing errors that prevent my tests from even running, which is highly problematic.
