### ISSUE TITLE
Difficulty running testem on github actions

### ISSUE THREAD

**Issue by asturur** [testem/testem#1415]
I'm trying to move my travisci setup to github actions.
one of my tests uses testem to run on firefox/chrome.
I have difficulties running it, the test start but never ends, and i see no output.

This is my action file:

```yml
# This workflow will do a clean install of node dependencies, build the library, run testem for firefox

name: Unit tests on Firefox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests on Firefox
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build:fast
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run testem ci --port 8080 -f testem.json -l Firefox
```

And this is what i see after i cancel the build after 30minutes:

![image](https://user-images.githubusercontent.com/1194048/104843242-d4652000-58c9-11eb-9728-c8c930d29c04.png)

Those are the logs:
https://github.com/fabricjs/fabric.js/pull/6811/checks?check_run_id=1716698233

Anyone knows how to make it work?
