### ISSUE TITLE
Add ci and dev specific configuration, and sections

### ISSUE THREAD

**Issue by airportyh** [testem/testem#264]
It would be convenient to be able to specify certain hooks to apply only to `ci` vs `dev`. One proposal is allowing ci and dev sections:

```
ci:
    before_tests: compile-scripts; start-server
dev:
    before_tests: start-server
```

With a fallback to the top-level `before_tests`. It might be nice to allow arbitrary sections too. Like a section for node tests vs another for browser tests - then when you run the node tests, it doesn't have to prep for any of the browser-related stuff. Example:

```
node:
    src_files:
        - lib/**/*.js
        - index.js
    launch: node index.js
web:
    before_tests: ./compile-scripts
    framework: mocha
    src_files:
        - public/js/**/*.js
```

But making this backwards compatible is a bit tricky. Also, the concept of launchers might need to be redefined somewhat.
