### ISSUE TITLE
All tests output as one test with CI when using Mocha-Casperjs?

### ISSUE THREAD

**Issue by KingScooty** [testem/testem#382]
I've come across a TAP reporting issue when using testem and mocha-casperjs.

The tap output just outputs 1 test has passed if all 13 of my tests pass using testem CI.

Testem CI output:
![Testem](http://cl.ly/image/341h1H3t0I2s/Screen%20Shot%202014-06-25%20at%2018.00.22.png)

Standard mocha-casper output:
![Mocha-Casper](http://cl.ly/image/382242153C1k/Screen%20Shot%202014-06-25%20at%2018.00.27.png)

Is there a way to get the Testem CI reporting all the tests properly?

This is my `testem.yml` file:

``` yml
framework: mocha+chai

src_files:
  - headless/*.js

launchers:

  Node:
    command: mocha-casperjs headless/index.js --casper-timeout=30000

  NodeCI:
    command: mocha-casperjs headless/index.js --reporter=tap --casper-timeout=30000

launch_in_ci:
  - NodeCI

launch_in_dev: 
  - Node
```
