### ISSUE TITLE
Can't traverse file paths or globs in subdirectories.

### ISSUE THREAD

**Issue by davemo** [testem/testem#39]
Hi, I was testing out testem and tried to configure it to run based on a complex file structure in an existing app, my config.yml looks like this: 

``` yaml
framework: jasmine
src_files:
- health/public/ui/default/js/vendor/jquery.min.js
- health/public/ui/default/js/vendor/jquery.datatables.min.js
- health/public/ui/default/js/vendor/jquery.peity.min.js
- health/public/ui/default
- health/public/tests/spec/helpers/*.js
- health/public/tests/spec/*-spec.js
```

I can connect browsers but testem can't find any files other than the ones directly in the same path as config.yml. Am I doing something wrong?
