### ISSUE TITLE
Tests on phantom js are hanging

### ISSUE THREAD

**Issue by thetutlage** [testem/testem#707]
Hi i am using Vagrant to run my tests on PhantomJs, they work fine on my machine using Chrome and firefox.

```
./node_modules/.bin/testem --version
0.9.11
```

```
phantomjs --version
1.9.0
```

```
./node_modules/.bin/testem launchers
PhantomJS     browser       ✔    ✔
```

## Config file
```yaml
framework: "mocha+chai"
serve_files:
  - browserified.js
src_files:
  - test/unit/*.spec.js
  - src/**/*.js
  - src/**/*.vue
before_tests: 'browserify -t vueify -t stringify test/unit/launcher.js -o browserified.js'
on_exit: 'rm browserified.js'
launch_in_dev:
  - Chrome
  - PhantomJS
  - node
```
