### ISSUE TITLE
mocha coffeescript example

### ISSUE THREAD

**Issue by andreineculau** [testem/testem#82]
I've found out that the coffeescript example (using jasmine as framework)
would benefit from a Mocha version

I don't know if this is Mocha specific, but this is what happens in different scenarios
# Scenario 1

``` yml
framework: mocha
before_tests: coffee -c src test
on_exit: rm src/*.js test/*.js
src_files:
- src/*.coffee
- test/*.coffee
launchers:
  Mocha:
    command: mocha -R tap test/*.coffee
    protocol: tap
launch_in_dev:
  - Mocha
launch_in_ci:
  - Mocha
```
- tests will start running and fail (coffee compiler still not done)
- tests will run again and pass (coffee compiler finished)

Same happens with `mocha -r coffee-script`
# Scenario 2

``` yml
framework: mocha
before_tests: coffee -c src test
on_exit: rm src/*.js test/*.js
src_files:
- src/*.coffee
- test/*.coffee
launchers:
  Mocha:
    command: mocha --compilers coffee:coffee-script -R tap test/*.coffee
    protocol: tap
launch_in_dev:
  - Mocha
launch_in_ci:
  - Mocha
```
- tests run twice, and pass both times
# Scenario 3

remove `before_tests` and `on_exit` for a smooth one-time passing tests

---

I have Scenario 3 with commented out `before_tests` and `on_exit` in live.

But I like Scenario 2 when testing locally, because of the line-numbers reported onto the JS compiled source, rather than the coffee source.
